# Generated by Django 5.1.2 on 2024-10-27 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_listndesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='listndesc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ListNDesc', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
