# Generated by Django 5.1.2 on 2024-11-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
